/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Resource = {
  _type: "resource";
  type?: "article" | "docs" | "repo" | "download" | "video";
  title?: string;
  description?: string;
  url?: string;
};

export type LearningOutcome = {
  _type: "learningOutcome";
  icon?:
    | "rocket"
    | "layers"
    | "zap"
    | "code"
    | "server"
    | "database"
    | "shield-check"
    | "gauge"
    | "puzzle"
    | "target";
  title?: string;
  description?: string;
};

export type LessonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "lesson";
};

export type Module = {
  _type: "module";
  title?: string;
  summary?: string;
  lessons?: Array<
    {
      _key: string;
    } & LessonReference
  >;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Lesson = {
  _id: string;
  _type: "lesson";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  videoUrl?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  duration?: number;
  freePreview?: boolean;
  studentCount?: number;
  notes?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  keyPoints?: Array<string>;
  proTip?: string;
  resources?: Array<
    {
      _key: string;
    } & Resource
  >;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type InstructorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "instructor";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Course = {
  _id: string;
  _type: "course";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  level?: "beginner" | "intermediate" | "advanced";
  price?: number;
  popular?: boolean;
  studentCount?: number;
  learningOutcomes?: Array<
    {
      _key: string;
    } & LearningOutcome
  >;
  instructor?: InstructorReference;
  category?: CategoryReference;
  modules?: Array<
    {
      _key: string;
    } & Module
  >;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type Instructor = {
  _id: string;
  _type: "instructor";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  expertise?: string;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Resource
  | LearningOutcome
  | LessonReference
  | Module
  | SanityImageAssetReference
  | Lesson
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | InstructorReference
  | CategoryReference
  | Course
  | Category
  | Instructor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../sanity/queries.ts
// Variable: COURSES_QUERY
// Query: *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) {   _id,  title,  "slug": slug.current,  summary,  coverImage,  level,  price,  popular,  studentCount,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalSeconds": math::sum(modules[].lessons[]->duration),  category->{ title, "slug": slug.current },  instructor->{ name, "slug": slug.current } }
export type COURSES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalSeconds: number | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  instructor: {
    name: string | null;
    slug: string | null;
  } | null;
}>;

// Source: ../sanity/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)] | order(title asc) { _id, title, "slug": slug.current, description }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
}>;

// Source: ../sanity/queries.ts
// Variable: COURSE_QUERY
// Query: *[_type == "course" && slug.current == $slug][0] {      _id,  title,  "slug": slug.current,  summary,  coverImage,  level,  price,  popular,  studentCount,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalSeconds": math::sum(modules[].lessons[]->duration),  category->{ title, "slug": slug.current },  instructor->{ name, "slug": slug.current },    learningOutcomes[] { _key, icon, title, description },    instructor->{ name, "slug": slug.current, photo, expertise },    modules[] {      _key,      title,      summary,      lessons[]->{ _id, title, "slug": slug.current, duration, freePreview }    }  }
export type COURSE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  summary: string | null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  level: "advanced" | "beginner" | "intermediate" | null;
  price: number | null;
  popular: boolean | null;
  studentCount: number | null;
  moduleCount: number | null;
  lessonCount: number | null;
  totalSeconds: number | null;
  category: {
    title: string | null;
    slug: string | null;
  } | null;
  instructor: {
    name: string | null;
    slug: string | null;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    expertise: string | null;
  } | null;
  learningOutcomes: Array<{
    _key: string;
    icon:
      | "code"
      | "database"
      | "gauge"
      | "layers"
      | "puzzle"
      | "rocket"
      | "server"
      | "shield-check"
      | "target"
      | "zap"
      | null;
    title: string | null;
    description: string | null;
  }> | null;
  modules: Array<{
    _key: string;
    title: string | null;
    summary: string | null;
    lessons: Array<{
      _id: string;
      title: string | null;
      slug: string | null;
      duration: number | null;
      freePreview: boolean | null;
    }> | null;
  }> | null;
} | null;

// Source: ../sanity/queries.ts
// Variable: LESSON_QUERY
// Query: *[_type == "lesson" && slug.current == $lessonSlug][0] {    _id,    title,    "slug": slug.current,    videoUrl,    poster,    duration,    freePreview,    studentCount,    notes,    keyPoints,    proTip,    resources[] { _key, type, title, description, url },    "course": *[_type == "course" && slug.current == $courseSlug && references(^._id)][0] {      _id,      title,      "slug": slug.current,      coverImage,      instructor->{ name, "slug": slug.current, photo, expertise },      modules[] {        _key,        title,        lessons[]->{ _id, title, "slug": slug.current, duration, freePreview }      }    }  }
export type LESSON_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  videoUrl: string | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  duration: number | null;
  freePreview: boolean | null;
  studentCount: number | null;
  notes: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  keyPoints: Array<string> | null;
  proTip: string | null;
  resources: Array<{
    _key: string;
    type: "article" | "docs" | "download" | "repo" | "video" | null;
    title: string | null;
    description: string | null;
    url: string | null;
  }> | null;
  course: {
    _id: string;
    title: string | null;
    slug: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    instructor: {
      name: string | null;
      slug: string | null;
      photo: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      } | null;
      expertise: string | null;
    } | null;
    modules: Array<{
      _key: string;
      title: string | null;
      lessons: Array<{
        _id: string;
        title: string | null;
        slug: string | null;
        duration: number | null;
        freePreview: boolean | null;
      }> | null;
    }> | null;
  } | null;
} | null;

// Source: ../sanity/queries.ts
// Variable: INSTRUCTOR_QUERY
// Query: *[_type == "instructor" && slug.current == $slug][0] {    _id,    name,    "slug": slug.current,    photo,    expertise,    bio,    "courses": *[_type == "course" && references(^._id)] | order(title asc) {   _id,  title,  "slug": slug.current,  summary,  coverImage,  level,  price,  popular,  studentCount,  "moduleCount": count(modules),  "lessonCount": count(modules[].lessons[]),  "totalSeconds": math::sum(modules[].lessons[]->duration),  category->{ title, "slug": slug.current },  instructor->{ name, "slug": slug.current } }  }
export type INSTRUCTOR_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  expertise: string | null;
  bio: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  courses: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    summary: string | null;
    coverImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    level: "advanced" | "beginner" | "intermediate" | null;
    price: number | null;
    popular: boolean | null;
    studentCount: number | null;
    moduleCount: number | null;
    lessonCount: number | null;
    totalSeconds: number | null;
    category: {
      title: string | null;
      slug: string | null;
    } | null;
    instructor: {
      name: string | null;
      slug: string | null;
    } | null;
  }>;
} | null;

// Source: ../sanity/queries.ts
// Variable: COURSE_SLUGS_QUERY
// Query: *[_type == "course" && defined(slug.current)].slug.current
export type COURSE_SLUGS_QUERY_RESULT = Array<string | null>;

// Source: ../sanity/queries.ts
// Variable: LESSON_PATHS_QUERY
// Query: *[_type == "course" && defined(slug.current)] {    "courseSlug": slug.current,    "lessonSlugs": modules[].lessons[]->slug.current  }
export type LESSON_PATHS_QUERY_RESULT = Array<{
  courseSlug: string | null;
  lessonSlugs: Array<string | null> | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "course" && defined(slug.current)] | order(popular desc, title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  coverImage,\n  level,\n  price,\n  popular,\n  studentCount,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalSeconds": math::sum(modules[].lessons[]->duration),\n  category->{ title, "slug": slug.current },\n  instructor->{ name, "slug": slug.current }\n }\n': COURSES_QUERY_RESULT;
    '\n  *[_type == "category" && defined(slug.current)] | order(title asc) { _id, title, "slug": slug.current, description }\n': CATEGORIES_QUERY_RESULT;
    '\n  *[_type == "course" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  coverImage,\n  level,\n  price,\n  popular,\n  studentCount,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalSeconds": math::sum(modules[].lessons[]->duration),\n  category->{ title, "slug": slug.current },\n  instructor->{ name, "slug": slug.current }\n,\n    learningOutcomes[] { _key, icon, title, description },\n    instructor->{ name, "slug": slug.current, photo, expertise },\n    modules[] {\n      _key,\n      title,\n      summary,\n      lessons[]->{ _id, title, "slug": slug.current, duration, freePreview }\n    }\n  }\n': COURSE_QUERY_RESULT;
    '\n  *[_type == "lesson" && slug.current == $lessonSlug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    videoUrl,\n    poster,\n    duration,\n    freePreview,\n    studentCount,\n    notes,\n    keyPoints,\n    proTip,\n    resources[] { _key, type, title, description, url },\n    "course": *[_type == "course" && slug.current == $courseSlug && references(^._id)][0] {\n      _id,\n      title,\n      "slug": slug.current,\n      coverImage,\n      instructor->{ name, "slug": slug.current, photo, expertise },\n      modules[] {\n        _key,\n        title,\n        lessons[]->{ _id, title, "slug": slug.current, duration, freePreview }\n      }\n    }\n  }\n': LESSON_QUERY_RESULT;
    '\n  *[_type == "instructor" && slug.current == $slug][0] {\n    _id,\n    name,\n    "slug": slug.current,\n    photo,\n    expertise,\n    bio,\n    "courses": *[_type == "course" && references(^._id)] | order(title asc) { \n  _id,\n  title,\n  "slug": slug.current,\n  summary,\n  coverImage,\n  level,\n  price,\n  popular,\n  studentCount,\n  "moduleCount": count(modules),\n  "lessonCount": count(modules[].lessons[]),\n  "totalSeconds": math::sum(modules[].lessons[]->duration),\n  category->{ title, "slug": slug.current },\n  instructor->{ name, "slug": slug.current }\n }\n  }\n': INSTRUCTOR_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)].slug.current\n': COURSE_SLUGS_QUERY_RESULT;
    '\n  *[_type == "course" && defined(slug.current)] {\n    "courseSlug": slug.current,\n    "lessonSlugs": modules[].lessons[]->slug.current\n  }\n': LESSON_PATHS_QUERY_RESULT;
  }
}
